In [1]:
import pandas as pd
import numpy as np

In [4]:
df_2022 = pd.read_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\raw\VENTE_DPT_PRODUIT_2022.csv.gz", sep=";")

In [5]:
df_2022.head(5)

,annee,code_departement,departement,amm,quantite_produit,conditionnement,eaj
0,2022,38,ISERE,8400255,40.4,K,Non
1,2022,33,GIRONDE,2190307,665.0,L,Non
2,2022,90,TERRITOIRE DE BELFORT,8800199,60.0,L,Non
3,2022,36,INDRE,2090042,326.9,K,Non
4,2022,64,PYRENEES-ATLANTIQUES,2170979,1.0,K,Non

In [ ]:
df_2022.describe()

         annee           amm  quantite_produit
count  60375.0  6.037500e+04      60375.000000
mean    2022.0  3.632400e+06       2849.724060
std        0.0  2.888393e+06      13997.514846
min     2022.0  1.030003e+06          0.000000
25%     2022.0  2.110033e+06         28.100000
50%     2022.0  2.160615e+06        199.500000
75%     2022.0  2.200893e+06       1240.000000
max     2022.0  9.900446e+06     809312.000000

In [7]:
df_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 60375 entries, 0 to 60374
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annee             60375 non-null  int64
 1   code_departement  60375 non-null  str
 2   departement       60375 non-null  str
 3   amm               60375 non-null  int64
 4   quantite_produit  60375 non-null  float64
 5   conditionnement   60375 non-null  str
 6   eaj               60375 non-null  str
dtypes: float64(1), int64(2), str(4)
memory usage: 3.2 MB

(60375, 7)