In [2]:
import pandas as pd
import numpy as np

In [3]:
df_2022 = pd.read_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\raw\VENTE_DPT_PRODUIT_2022.csv.gz", sep=";")
df_2023 = pd.read_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\raw\VENTE_DPT_PRODUIT_2023.csv.gz", sep=";")
df_2024 = pd.read_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\raw\VENTE_DPT_PRODUIT_2024.csv.gz", sep=";")

## OBSERVATION
- amm : identifiant réglementaire du produit (pas une mesure). eaj : autorisation d'usage jardin amateur (oui/non).
- Les quantités de substances actives sont exprimées en kilogrammes.
- (16 amm récurrents, hypothèse "arrondi ou déclaration résiduelle" non confirmée)

In [4]:
df_2022.info()

<class 'pandas.DataFrame'>
RangeIndex: 60375 entries, 0 to 60374
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annee             60375 non-null  int64
 1   code_departement  60375 non-null  str
 2   departement       60375 non-null  str
 3   amm               60375 non-null  int64
 4   quantite_produit  60375 non-null  float64
 5   conditionnement   60375 non-null  str
 6   eaj               60375 non-null  str
dtypes: float64(1), int64(2), str(4)
memory usage: 3.2 MB

In [5]:
df_2023.info()

<class 'pandas.DataFrame'>
RangeIndex: 60043 entries, 0 to 60042
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annee             60043 non-null  int64
 1   code_departement  60043 non-null  str
 2   departement       60043 non-null  str
 3   amm               60043 non-null  int64
 4   quantite_produit  60043 non-null  float64
 5   conditionnement   60043 non-null  str
 6   eaj               60043 non-null  str
dtypes: float64(1), int64(2), str(4)
memory usage: 3.2 MB

In [6]:
df_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 60630 entries, 0 to 60629
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   annee             60630 non-null  int64
 1   code_departement  60630 non-null  str
 2   departement       60630 non-null  str
 3   amm               60630 non-null  int64
 4   quantite_produit  60630 non-null  float64
 5   conditionnement   60630 non-null  str
 6   eaj               60630 non-null  str
dtypes: float64(1), int64(2), str(4)
memory usage: 3.2 MB

In [20]:
a = df_2022["quantite_produit"]==0
a.sum()

np.int64(68)

In [30]:
pd.set_option('display.max_rows',None)

In [33]:
df_2022[df_2022['quantite_produit']==0].head(5)

,annee,code_departement,departement,amm,quantite_produit,conditionnement,eaj
3258,2022,90,TERRITOIRE DE BELFORT,2180865,0.0,L,Non
3917,2022,19,CORREZE,2200078,0.0,L,Non
4174,2022,31,HAUTE-GARONNE,2020099,0.0,L,Non
4289,2022,38,ISERE,9900123,0.0,K,Non
4310,2022,06,ALPES-MARITIMES,2140001,0.0,K,Non

In [34]:
df_2023[df_2023['quantite_produit']==0].head(5)

,annee,code_departement,departement,amm,quantite_produit,conditionnement,eaj
1216,2023,33,GIRONDE,2180865,0.0,L,Non
1271,2023,18,CHER,8900700,0.0,K,Oui
1499,2023,42,LOIRE,9800514,0.0,K,Non
1914,2023,44,LOIRE-ATLANTIQUE,2080112,0.0,L,Non
3280,2023,32,GERS,9800402,0.0,L,Oui

In [35]:
df_2024[df_2024['quantite_produit']==0].head(5)

,annee,code_departement,departement,amm,quantite_produit,conditionnement,eaj
432,2024,62,PAS-DE-CALAIS,2200736,0.0,L,Non
711,2024,59,NORD,2180865,0.0,L,Non
1827,2024,22,COTES-D'ARMOR,2200736,0.0,L,Non
2646,2024,41,LOIR-ET-CHER,2180275,0.0,K,Oui
3536,2024,14,CALVADOS,2000201,0.0,L,Non

In [36]:
amm_2022 = set(df_2022[df_2022["quantite_produit"]==0]["amm"])
amm_2023 = set(df_2023[df_2023["quantite_produit"]==0]["amm"])
amm_2024 = set(df_2024[df_2024["quantite_produit"]==0]["amm"])

amm_2022 & amm_2023 & amm_2024

{2000017,
 2070108,
 2140001,
 2140104,
 2170230,
 2170700,
 2171253,
 2180275,
 2180766,
 2180865,
 2200078,
 2200736,
 2220753,
 8500351,
 9200262,
 9800262}

In [37]:
for df in [df_2022, df_2023, df_2024]:
    # amm en str
    df["amm"] = df["amm"].astype(str)

    # doublons
    print("Doublons :", df.duplicated().sum())

    # outliers hautes valeurs (quantite_produit)
    print(df["quantite_produit"].describe())

    # cohérence catégorielles
    print("conditionnement :", df["conditionnement"].unique())
    print("eaj :", df["eaj"].unique())
    print("code_departement :", sorted(df["code_departement"].unique()))

Doublons : 0
count     60375.000000
mean       2849.724060
std       13997.514846
min           0.000000
25%          28.100000
50%         199.500000
75%        1240.000000
max      809312.000000
Name: quantite_produit, dtype: float64
conditionnement : <StringArray>
['K', 'L']
Length: 2, dtype: str
eaj : <StringArray>
['Non', 'Oui']
Length: 2, dtype: str
code_departement : ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '973', '974']
Doublons : 0
count     60043.000000
mean       2828.591016
std       13881.280984
min           0.000000
25%          29.000000
50%         200.000000
75%        1220.000000
max      895796.000000
Name: quantite_produit, dtype: float64
conditionnement : <StringArray>
['K', 'L']
Length: 2, dtype: str
eaj : <StringArray>
['Non', 'Oui']
Length: 2, dtype: str
code_departement : ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '974']
Doublons : 0
count    6.063000e+04
mean     3.260509e+03
std      1.653388e+04
min      0.000000e+00
25%      3.000000e+01
50%      2.100000e+02
75%      1.310000e+03
max      1.039375e+06
Name: quantite_produit, dtype: float64
conditionnement : <StringArray>
['K', 'L']
Length: 2, dtype: str
eaj : <StringArray>
['Non', 'Oui']
Length: 2, dtype: str
code_departement : ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '21', '22', '23', '24', '25', '26', '27', '28', '29', '2A', '2B', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '971', '972', '974']

In [39]:
df_2022.to_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\processed/ventes_2022_clean.csv", index=False, sep=";", encoding="utf-8")
df_2023.to_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\processed/ventes_2023_clean.csv", index=False, sep=";", encoding="utf-8")
df_2024.to_csv(r"C:\Users\mosca\Documents\GitHub\ventes-pesticides\data\processed/ventes_2024_clean.csv", index=False, sep=";", encoding="utf-8")